version: '3'

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      - 'MARIADB_ROOT_PASSWORD=密码' #改这里
    volumes:
      - ./media/:/var/lib/mysql
  lwt:
    image: lwt:latest
    restart: always
    environment:
      - 'MARIADB_SERVER=mariadb'
      - 'MARIADB_ROOT_PASSWORD=密码' #和上面的一样
    ports:
      - '8080:80' #如果需要改端口的话改8080的地方
    depends_on:
      - mariadb
